import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Link } from "@nextui-org/react";
import './page.modules.css'
import UIProvider from "./dashboard/ui/UIProvider";
import { Nav } from "./dashboard/components/Nav";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TFA",
  description: "Generated by UCI",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="md:w-full w-[100vh] md:h-full h-[100vh]">
      <body>
          <UIProvider>
            <Providers>
              <main className="fadeIn">
              {children}
              </main>
            </Providers>
          </UIProvider>
      </body>
    </html>
  );
}

